
on:
  workflow_dispatch:
  # push:
  #   branches: main
  # pull_request:
  #   branches: main

name: rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    - run: R CMD build .

    - run: docker pull kalibera/rchk:latest
    - name: run rchk
      run: |
          pkgtar=$(ls reticulate_*.tar.gz)
          mkdir -p rchk/packages
          mv $pkgtar rchk/packages/
          cd rchk
          docker run -v `pwd`/packages:/rchk/packages kalibera/rchk:latest /rchk/packages/$pkgtar > rchk.log 2>&1
          cat rchk.log

    - name: upload rchk log
      uses: actions/upload-artifact@v4
      with:
        name: rchk-log
        path: rchk/packages/rchk.log
